/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as FindAccountRouteImport } from './routes/find-account.tsx'
import { Route as Video_backgroundRouteRouteImport } from './routes/_video_background/route.tsx'
import { Route as IndexRouteImport } from './routes/index.tsx'
import { Route as SecurityIndexRouteImport } from './routes/security/index.tsx'
import { Route as Video_backgroundSignupRedirectRouteImport } from './routes/_video_background/signup-redirect.tsx'
import { Route as Video_backgroundSignupRouteImport } from './routes/_video_background/signup.tsx'
import { Route as Video_backgroundLoginRouteImport } from './routes/_video_background/login.tsx'

const FindAccountRoute = FindAccountRouteImport.update({
  id: '/find-account',
  path: '/find-account',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/find-account.lazy.tsx').then((d) => d.Route),
)
const Video_backgroundRouteRoute = Video_backgroundRouteRouteImport.update({
  id: '/_video_background',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/security/index.lazy.tsx').then((d) => d.Route),
)
const Video_backgroundSignupRedirectRoute =
  Video_backgroundSignupRedirectRouteImport.update({
    id: '/signup-redirect',
    path: '/signup-redirect',
    getParentRoute: () => Video_backgroundRouteRoute,
  } as any)
const Video_backgroundSignupRoute = Video_backgroundSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => Video_backgroundRouteRoute,
} as any).lazy(() =>
  import('./routes/_video_background/signup.lazy.tsx').then((d) => d.Route),
)
const Video_backgroundLoginRoute = Video_backgroundLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => Video_backgroundRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-account': typeof FindAccountRoute
  '/login': typeof Video_backgroundLoginRoute
  '/signup': typeof Video_backgroundSignupRoute
  '/signup-redirect': typeof Video_backgroundSignupRedirectRoute
  '/security/': typeof SecurityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-account': typeof FindAccountRoute
  '/login': typeof Video_backgroundLoginRoute
  '/signup': typeof Video_backgroundSignupRoute
  '/signup-redirect': typeof Video_backgroundSignupRedirectRoute
  '/security': typeof SecurityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_video_background': typeof Video_backgroundRouteRouteWithChildren
  '/find-account': typeof FindAccountRoute
  '/_video_background/login': typeof Video_backgroundLoginRoute
  '/_video_background/signup': typeof Video_backgroundSignupRoute
  '/_video_background/signup-redirect': typeof Video_backgroundSignupRedirectRoute
  '/security/': typeof SecurityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/find-account'
    | '/login'
    | '/signup'
    | '/signup-redirect'
    | '/security/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/find-account'
    | '/login'
    | '/signup'
    | '/signup-redirect'
    | '/security'
  id:
    | '__root__'
    | '/'
    | '/_video_background'
    | '/find-account'
    | '/_video_background/login'
    | '/_video_background/signup'
    | '/_video_background/signup-redirect'
    | '/security/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Video_backgroundRouteRoute: typeof Video_backgroundRouteRouteWithChildren
  FindAccountRoute: typeof FindAccountRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/find-account': {
      id: '/find-account'
      path: '/find-account'
      fullPath: '/find-account'
      preLoaderRoute: typeof FindAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_video_background': {
      id: '/_video_background'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof Video_backgroundRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_video_background/signup-redirect': {
      id: '/_video_background/signup-redirect'
      path: '/signup-redirect'
      fullPath: '/signup-redirect'
      preLoaderRoute: typeof Video_backgroundSignupRedirectRouteImport
      parentRoute: typeof Video_backgroundRouteRoute
    }
    '/_video_background/signup': {
      id: '/_video_background/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof Video_backgroundSignupRouteImport
      parentRoute: typeof Video_backgroundRouteRoute
    }
    '/_video_background/login': {
      id: '/_video_background/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof Video_backgroundLoginRouteImport
      parentRoute: typeof Video_backgroundRouteRoute
    }
  }
}

interface Video_backgroundRouteRouteChildren {
  Video_backgroundLoginRoute: typeof Video_backgroundLoginRoute
  Video_backgroundSignupRoute: typeof Video_backgroundSignupRoute
  Video_backgroundSignupRedirectRoute: typeof Video_backgroundSignupRedirectRoute
}

const Video_backgroundRouteRouteChildren: Video_backgroundRouteRouteChildren = {
  Video_backgroundLoginRoute: Video_backgroundLoginRoute,
  Video_backgroundSignupRoute: Video_backgroundSignupRoute,
  Video_backgroundSignupRedirectRoute: Video_backgroundSignupRedirectRoute,
}

const Video_backgroundRouteRouteWithChildren =
  Video_backgroundRouteRoute._addFileChildren(
    Video_backgroundRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Video_backgroundRouteRoute: Video_backgroundRouteRouteWithChildren,
  FindAccountRoute: FindAccountRoute,
  SecurityIndexRoute: SecurityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
