name: E2E Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build-images:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Build images
        run: docker compose build account-center-be

      - name: Export image
        run: docker save -o account-center-be.tar ijia/account-center-be

      - uses: actions/upload-artifact@v7
        with:
          name: account-center-be-image-${{ github.sha }}
          path: account-center-be.tar
          overwrite: true

  e2e:
    runs-on: ubuntu-22.04
    needs: build-images
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2

      - name: Install dependencies
        run: deno install --frozen
        working-directory: ./e2e

      - uses: actions/cache@v4 #https://playwright.dev/docs/browsers#managing-browser-binaries
        with:
          path: /home/runner/.cache/ms-playwright
          key: playwright-browser-${{ hashFiles('e2e/package.json') }}
      - name: Install browser
        run: deno x playwright install chromium webkit firefox --with-deps
        working-directory: ./e2e

      - uses: actions/download-artifact@v4
        with:
          name: account-center-be-image-${{ github.sha }}

      - name: Load account-center-be image
        run: docker load -i account-center-be.tar

      - name: Build remaining local services
        run: docker compose build ijiadb redis account-center-fe

      - name: Start services
        run: docker compose up -d
      - name: E2E test
        continue-on-error: true
        run: deno task e2e:run
        env:
          DATABASE_URL: "postgresql://postgres@localhost:5442/ijia"
          WEB_URL: "http://localhost:9002"
        id: e2e
        working-directory: ./e2e

      - uses: actions/upload-artifact@v7
        if: ${{steps.e2e.outcome=='failure'}}
        with:
          name: playwright-report
          path: e2e/playwright-report/
      - name: Result
        if: ${{steps.e2e.outcome=='failure'}}
        run: exit 1
